title: quarantineDataScience
email: admin@distilleriesfightingcovid.com
description: >- 
  This is the group site for the volunteers behind distillersfightingcovid, covidmodeling.com, and other products.
  A group of nerds from SMU working remotely from all of our homes. Staying inside, trying to help make a difference.
baseurl: "" # the subpath of your site, e.g. /blog
url: "quarantinedatascience.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: bulma-clean-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
#   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
